/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Dynamic: typeof import('solid-js/web').Dynamic
  const ErrorBoundary: typeof import('solid-js').ErrorBoundary
  const For: typeof import('solid-js').For
  const IconHeroiconsArrowPath: typeof import('~icons/heroicons/arrow-path.jsx').default
  const IconHeroiconsBars3: typeof import('~icons/heroicons/bars3.jsx').default
  const IconHeroiconsBuildingOffice2: typeof import('~icons/heroicons/building-office2.jsx').default
  const IconHeroiconsCheckCircle: typeof import('~icons/heroicons/check-circle.jsx').default
  const IconHeroiconsChevronDown: typeof import('~icons/heroicons/chevron-down.jsx').default
  const IconHeroiconsChevronDown16Solid: typeof import('~icons/heroicons/chevron-down16-solid.jsx').default
  const IconHeroiconsChevronUp16Solid: typeof import('~icons/heroicons/chevron-up16-solid.jsx').default
  const IconHeroiconsChevronUpDown16Solid: typeof import('~icons/heroicons/chevron-up-down16-solid.jsx').default
  const IconHeroiconsCog6Tooth: typeof import('~icons/heroicons/cog6-tooth.jsx').default
  const IconHeroiconsExclamationCircle: typeof import('~icons/heroicons/exclamation-circle.jsx').default
  const IconHeroiconsExclamationTriangle: typeof import('~icons/heroicons/exclamation-triangle.jsx').default
  const IconHeroiconsEye: typeof import('~icons/heroicons/eye.jsx').default
  const IconHeroiconsEyeSlash: typeof import('~icons/heroicons/eye-slash.jsx').default
  const IconHeroiconsInformationCircle: typeof import('~icons/heroicons/information-circle.jsx').default
  const IconHeroiconsMagnifyingGlass: typeof import('~icons/heroicons/magnifying-glass.jsx').default
  const IconHeroiconsOutlineBuildingOffice2: typeof import('~icons/heroicons-outline/building-office2.jsx').default
  const IconHeroiconsOutlineUserGroup: typeof import('~icons/heroicons-outline/user-group.jsx').default
  const IconHeroiconsPhoto: typeof import('~icons/heroicons/photo.jsx').default
  const IconHeroiconsPlus: typeof import('~icons/heroicons/plus.jsx').default
  const IconHeroiconsUserGroup: typeof import('~icons/heroicons/user-group.jsx').default
  const IconHeroiconsWrench: typeof import('~icons/heroicons/wrench.jsx').default
  const IconHeroiconsXCircle: typeof import('~icons/heroicons/x-circle.jsx').default
  const IconHeroiconsXMark: typeof import('~icons/heroicons/x-mark.jsx').default
  const IconHeroiconsXMark16Solid: typeof import('~icons/heroicons/x-mark16-solid.jsx').default
  const Index: typeof import('solid-js').Index
  const Link: typeof import('@solidjs/router').Link
  const Match: typeof import('solid-js').Match
  const NavLink: typeof import('@solidjs/router').NavLink
  const Navigate: typeof import('@solidjs/router').Navigate
  const Outlet: typeof import('@solidjs/router').Outlet
  const Portal: typeof import('solid-js/web').Portal
  const Route: typeof import('@solidjs/router').Route
  const Router: typeof import('@solidjs/router').Router
  const Routes: typeof import('@solidjs/router').Routes
  const Show: typeof import('solid-js').Show
  const Suspense: typeof import('solid-js').Suspense
  const SuspenseList: typeof import('solid-js').SuspenseList
  const Switch: typeof import('solid-js').Switch
  const XButton: typeof import('./src/components/basic/XButton').XButton
  const XButtonAsync: typeof import('./src/components/advance/XButtonAsync').XButtonAsync
  const XCheckbox: typeof import('./src/components/basic/XCheckbox').XCheckbox
  const XDialog: typeof import('./src/components/basic/XDialog').XDialog
  const XFloating: typeof import('./src/components/basic/XFloating').XFloating
  const XForm: typeof import('./src/components/basic/XForm').XForm
  const XFormContext: typeof import('./src/components/basic/XForm').XFormContext
  const XFormItem: typeof import('./src/components/basic/XForm').XFormItem
  const XFormItemContext: typeof import('./src/components/basic/XForm').XFormItemContext
  const XFormRemote: typeof import('./src/components/advance/XFormRemote').XFormRemote
  const XInput: typeof import('./src/components/basic/XInput').XInput
  const XMessage: typeof import('./src/components/basic/XMessage').XMessage
  const XPagination: typeof import('./src/components/basic/XPagination').XPagination
  const XReconfirm: typeof import('./src/components/advance/XReconfirm').XReconfirm
  const XSelect: typeof import('./src/components/basic/XSelect').XSelect
  const XSelectRemote: typeof import('./src/components/advance/XSelectRemote').XSelectRemote
  const XTable: typeof import('./src/components/basic/XTable').XTable
  const XTableRemote: typeof import('./src/components/advance/XTableRemote').XTableRemote
  const XTableRemoteColumnHeaderContext: typeof import('./src/components/advance/XTableRemote').XTableRemoteColumnHeaderContext
  const XTableRemoteContext: typeof import('./src/components/advance/XTableRemote').XTableRemoteContext
  const XTag: typeof import('./src/components/basic/XTag').XTag
  const XTagLookup: typeof import('./src/components/advance/XTagLookup').XTagLookup
  const XTextarea: typeof import('./src/components/basic/XTextarea').XTextarea
  const XTooltip: typeof import('./src/components/basic/XTooltip').XTooltip
  const XTree: typeof import('./src/components/basic/XTree').XTree
  const XTreeNode: typeof import('./src/components/basic/XTree').XTreeNode
  const XTreeRemote: typeof import('./src/components/advance/XTreeRemote').XTreeRemote
  const XUpload: typeof import('./src/components/basic/XUpload').XUpload
  const XUploadAliyun: typeof import('./src/components/advance/XUploadAliyun').XUploadAliyun
  const XUploadPictureList: typeof import('./src/components/basic/XUpload').XUploadPictureList
  const XUploadRemote: typeof import('./src/components/advance/XUploadRemote').XUploadRemote
  const XUploadUploadedFileList: typeof import('./src/components/basic/XUpload').XUploadUploadedFileList
  const XUploadUploadedImageList: typeof import('./src/components/basic/XUpload').XUploadUploadedImageList
  const XUploadUploadedImgList: typeof import('./src/components/basic/XUpload').XUploadUploadedImgList
  const XUploadUploadingList: typeof import('./src/components/basic/XUpload').XUploadUploadingList
  const _mergeSearchString: typeof import('@solidjs/router')._mergeSearchString
  const adminUserFormRemoteItems: typeof import('./src/business/adminUser').adminUserFormRemoteItems
  const adminUserTableRemoteColumns: typeof import('./src/business/adminUser').adminUserTableRemoteColumns
  const batch: typeof import('solid-js').batch
  const children: typeof import('solid-js').children
  const constructionGuidanceFormRemoteItems: typeof import('./src/business/constructionGuidance').constructionGuidanceFormRemoteItems
  const constructionGuidanceStepFormRemoteItems: typeof import('./src/business/constructionGuidanceStep').constructionGuidanceStepFormRemoteItems
  const constructionGuidanceStepTableRemoteColumns: typeof import('./src/business/constructionGuidanceStep').constructionGuidanceStepTableRemoteColumns
  const constructionGuidanceTableRemoteColumns: typeof import('./src/business/constructionGuidance').constructionGuidanceTableRemoteColumns
  const createAjax: typeof import('./src/utils/ajax').createAjax
  const createContext: typeof import('solid-js').createContext
  const createDeferred: typeof import('solid-js').createDeferred
  const createEffect: typeof import('solid-js').createEffect
  const createFormRemoteItems: typeof import('./src/utils/factory').createFormRemoteItems
  const createIntegration: typeof import('@solidjs/router').createIntegration
  const createListDetailGlue: typeof import('./src/utils/glue').createListDetailGlue
  const createListListGlue: typeof import('./src/utils/glue').createListListGlue
  const createMemo: typeof import('solid-js').createMemo
  const createMutable: typeof import('solid-js/store').createMutable
  const createRenderEffect: typeof import('solid-js').createRenderEffect
  const createResource: typeof import('solid-js').createResource
  const createRoot: typeof import('solid-js').createRoot
  const createSelector: typeof import('solid-js').createSelector
  const createSignal: typeof import('solid-js').createSignal
  const createStorage: typeof import('./src/utils/storage').createStorage
  const createStore: typeof import('solid-js/store').createStore
  const createTableColumns: typeof import('./src/utils/factory').createTableColumns
  const createTableRemoteColumns: typeof import('./src/utils/factory').createTableRemoteColumns
  const cva: typeof import('class-variance-authority').cva
  const cx: typeof import('class-variance-authority').cx
  const debounce: typeof import('./src/utils/debounce').debounce
  const departmentFormRemoteItems: typeof import('./src/business/department').departmentFormRemoteItems
  const departmentMemberFormRemoteItems: typeof import('./src/business/departmentMember').departmentMemberFormRemoteItems
  const departmentMemberTableRemoteColumns: typeof import('./src/business/departmentMember').departmentMemberTableRemoteColumns
  const departmentTableRemoteColumns: typeof import('./src/business/department').departmentTableRemoteColumns
  const hashIntegration: typeof import('@solidjs/router').hashIntegration
  const hydrate: typeof import('solid-js/web').hydrate
  const indexArray: typeof import('solid-js').indexArray
  const isServer: typeof import('solid-js/web').isServer
  const lazy: typeof import('solid-js').lazy
  const mapArray: typeof import('solid-js').mapArray
  const materialCategoryFormRemoteItems: typeof import('./src/business/materialCategory').materialCategoryFormRemoteItems
  const materialFormRemoteItems: typeof import('./src/business/material').materialFormRemoteItems
  const materialTableRemoteColumns: typeof import('./src/business/material').materialTableRemoteColumns
  const mergeProps: typeof import('solid-js').mergeProps
  const message: typeof import('./src/components/basic/XMessage').message
  const normalizeIntegration: typeof import('@solidjs/router').normalizeIntegration
  const observable: typeof import('solid-js').observable
  const on: typeof import('solid-js').on
  const onCleanup: typeof import('solid-js').onCleanup
  const onError: typeof import('solid-js').onError
  const onMount: typeof import('solid-js').onMount
  const pathIntegration: typeof import('@solidjs/router').pathIntegration
  const popup: typeof import('./src/utils/popup').popup
  const produce: typeof import('solid-js/store').produce
  const reconcile: typeof import('solid-js/store').reconcile
  const render: typeof import('solid-js/web').render
  const renderToStream: typeof import('solid-js/web').renderToStream
  const renderToString: typeof import('solid-js/web').renderToString
  const renderToStringAsync: typeof import('solid-js/web').renderToStringAsync
  const request: typeof import('./src/utils/ajax').request
  const splitProps: typeof import('solid-js').splitProps
  const staticIntegration: typeof import('@solidjs/router').staticIntegration
  const untrack: typeof import('solid-js').untrack
  const useContext: typeof import('solid-js').useContext
  const useHref: typeof import('@solidjs/router').useHref
  const useIsRouting: typeof import('@solidjs/router').useIsRouting
  const useLoading: typeof import('./src/utils/loading').useLoading
  const useLocation: typeof import('@solidjs/router').useLocation
  const useMatch: typeof import('@solidjs/router').useMatch
  const useNavigate: typeof import('@solidjs/router').useNavigate
  const useOssStore: typeof import('./src/stores/oss').useOssStore
  const useParams: typeof import('@solidjs/router').useParams
  const useResolvedPath: typeof import('@solidjs/router').useResolvedPath
  const useRouteData: typeof import('@solidjs/router').useRouteData
  const useRoutes: typeof import('@solidjs/router').useRoutes
  const useSearchParams: typeof import('@solidjs/router').useSearchParams
  const useTransition: typeof import('solid-js').useTransition
  const useUserStore: typeof import('./src/stores/user').useUserStore
}
// for type re-export
declare global {
  // @ts-ignore
  export type { XButtonAsyncProps } from './src/components/advance/XButtonAsync'
  import('./src/components/advance/XButtonAsync')
  // @ts-ignore
  export type { XFormRemoteExpose, XFormRemoteItemConfig, XFormRemoteProps } from './src/components/advance/XFormRemote'
  import('./src/components/advance/XFormRemote')
  // @ts-ignore
  export type { XReconfirmProps } from './src/components/advance/XReconfirm'
  import('./src/components/advance/XReconfirm')
  // @ts-ignore
  export type { XSelectRemoteProps } from './src/components/advance/XSelectRemote'
  import('./src/components/advance/XSelectRemote')
  // @ts-ignore
  export type { XTableRemoteColumnConfig, XTableRemoteExpose, XTableRemoteProps, XTableRemoteUi } from './src/components/advance/XTableRemote'
  import('./src/components/advance/XTableRemote')
  // @ts-ignore
  export type { XTagLookupProps } from './src/components/advance/XTagLookup'
  import('./src/components/advance/XTagLookup')
  // @ts-ignore
  export type { XTreeRemoteExpose, XTreeRemoteProps } from './src/components/advance/XTreeRemote'
  import('./src/components/advance/XTreeRemote')
  // @ts-ignore
  export type { ButtonColors, XButtonProps } from './src/components/basic/XButton'
  import('./src/components/basic/XButton')
  // @ts-ignore
  export type { XCheckboxProps } from './src/components/basic/XCheckbox'
  import('./src/components/basic/XCheckbox')
  // @ts-ignore
  export type { XDialogProps, XDialogUi } from './src/components/basic/XDialog'
  import('./src/components/basic/XDialog')
  // @ts-ignore
  export type { XFloatingExpose, XFloatingProps, XFloatingUi } from './src/components/basic/XFloating'
  import('./src/components/basic/XFloating')
  // @ts-ignore
  export type { XFormExpose, XFormItemProps, XFormItemValidation, XFormProps } from './src/components/basic/XForm'
  import('./src/components/basic/XForm')
  // @ts-ignore
  export type { XInputExpose, XInputProps, XInputType } from './src/components/basic/XInput'
  import('./src/components/basic/XInput')
  // @ts-ignore
  export type { XPaginationProps } from './src/components/basic/XPagination'
  import('./src/components/basic/XPagination')
  // @ts-ignore
  export type { XSelectOptionConfig, XSelectProps } from './src/components/basic/XSelect'
  import('./src/components/basic/XSelect')
  // @ts-ignore
  export type { XTableColumnConfig, XTableColumnUserConfig, XTableProps } from './src/components/basic/XTable'
  import('./src/components/basic/XTable')
  // @ts-ignore
  export type { TagColors, XTagProps } from './src/components/basic/XTag'
  import('./src/components/basic/XTag')
  // @ts-ignore
  export type { XTextareaProps } from './src/components/basic/XTextarea'
  import('./src/components/basic/XTextarea')
  // @ts-ignore
  export type { TooltipColors, XTooltipProps } from './src/components/basic/XTooltip'
  import('./src/components/basic/XTooltip')
  // @ts-ignore
  export type { XTreeNodeConfig, XTreeNodeProps, XTreeProps, XTreeSharedProps } from './src/components/basic/XTree'
  import('./src/components/basic/XTree')
  // @ts-ignore
  export type { XUploadProps } from './src/components/basic/XUpload'
  import('./src/components/basic/XUpload')
}
